name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
        matrix:
            python-version: [3.7, 3.8, 3.9, 3.11]
            os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        make install

    - name: Lint with flake8
      run: |
        make lint

    - name: Format with black
      run: |
        make format

    - name: Run Tests
      run: |
        make test
